<?php
declare(strict_types=1);
require_once __DIR__.'/../standalone/bootstrap.php';
require_once __DIR__.'/../autoloader.php';
require_once __DIR__.'/../Repository/ConfigManagerRepository.php';
require_once __DIR__.'/../Service/ConfigManagerService.php';
require_once __DIR__.'/../Controller/ConfigManagerController.php';
require_once __DIR__.'/../lib/config_manager_runtime.php';
if (!mmbb_has_service('ConfigManager')) { http_response_code(403); echo 'Forbidden'; exit; }
use ConfigManager\Repository\ConfigManagerRepository; use ConfigManager\Service\ConfigManagerService; use ConfigManager\Controller\ConfigManagerController;
if(session_status()===PHP_SESSION_NONE)session_start(); if(empty($_SESSION['csrf_token']))$_SESSION['csrf_token']=bin2hex(random_bytes(32)); $csrf=(string)$_SESSION['csrf_token'];
function cb_json(array $x,int $s=200):never{http_response_code($s);header('Content-Type: application/json; charset=utf-8');header('Cache-Control:no-store');echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function cb_servers():array{return cm_load_config_manager_servers(__DIR__.'/../config/config.php');}
function cb_find(array $servers,string $name):array{foreach($servers as $s)if(strcasecmp((string)($s['name']??''),$name)===0)return $s;throw new RuntimeException('Unbekannter Server.',404);}
function cb_ctl(array $server):ConfigManagerController{return new ConfigManagerController(new ConfigManagerService(new ConfigManagerRepository($server)));}
function cb_body():array{$x=json_decode((string)file_get_contents('php://input'),true);if(!is_array($x))throw new InvalidArgumentException('Ungültiges JSON.');return $x;}
function cb_unwrap(array $r):array{$c=(int)($r['http_code']??500);$x=is_array($r['response']??null)?$r['response']:[];if($c<200||$c>=300||empty($x['ok']))throw new RuntimeException((string)($x['error']??('Agent HTTP '.$c)),$c>=400&&$c<=599?$c:502);return $x;}
try{
 $servers=cb_servers();
 if(($_GET['api']??'')==='summary') {
  $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
  $host = preg_replace('/[^A-Za-z0-9.:-]/','',(string)($_SERVER['HTTP_HOST']??'config-manager.local')) ?: 'config-manager.local';
  $base = rtrim((string)(cfg('CONFIG_MANAGER_PUBLIC_BASE_URL') ?: ($scheme.'://'.$host)),'/');
  cb_json(['ok'=>true,
    'servers'=>array_map(fn($s)=>['name'=>(string)($s['name']??'')],$servers),
  ]);
}
 if(($_GET['api']??'')==='load'){ $srv=cb_find($servers,trim((string)($_GET['server']??''))); cb_json(['ok'=>true,'info'=>cb_unwrap(cb_ctl($srv)->getClientBaselineInfo())]); }
 if($_SERVER['REQUEST_METHOD']==='POST'){
  $in=cb_body(); if(!hash_equals($csrf,(string)($in['csrf_token']??''))) throw new RuntimeException('CSRF fehlgeschlagen.',403); $srv=cb_find($servers,trim((string)($in['server_name']??''))); $ctl=cb_ctl($srv); $a=(string)($in['action']??'');
  if($a==='monit_config')cb_json(['ok'=>true,'result'=>cb_unwrap($ctl->saveClientMonitBaseline((array)($in['config']??[])))]);
  if($a==='monit_test')cb_json(['ok'=>true,'result'=>cb_unwrap($ctl->testClientMonitBaseline())]);
  throw new RuntimeException('Unbekannte Aktion.',400);
 }
}catch(Throwable $e){$c=(int)$e->getCode();cb_json(['ok'=>false,'error'=>$e->getMessage()],$c>=400&&$c<=599?$c:500);}
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Managed Hosts – Baseline</title><?php require MMBB_UI.'/includes/css.php';?><style>.bl-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1.3fr);gap:.8rem}.bl-card{border:1px solid var(--bs-border-color);border-radius:.6rem;padding:1rem;background:var(--bs-body-bg)}.bl-kv{display:grid;grid-template-columns:150px 1fr;gap:.3rem .8rem}.bl-sep{border-top:1px solid var(--bs-border-color);margin:1rem 0}.bl-good{color:var(--bs-success)}.bl-bad{color:var(--bs-danger)}.bl-job{border:1px solid var(--bs-border-color);border-radius:.45rem;padding:.65rem .75rem;background:var(--bs-tertiary-bg);margin-top:.75rem}.bl-job-head{display:flex;justify-content:space-between;gap:.75rem;font-size:.82rem;font-weight:600}.bl-job .progress{height:.55rem;margin:.45rem 0}.bl-install-list{font-size:.78rem;margin:.65rem 0 0;padding-left:1.1rem;color:var(--bs-secondary-color)}.bl-install-list code{font-size:.74rem}.bl-repo{border-left:4px solid var(--bs-primary);background:var(--bs-tertiary-bg)}@media(max-width:1000px){.bl-grid{grid-template-columns:1fr}}</style></head><body>
<?php require __DIR__.'/../standalone/layout/sidebar.php';?>
<main class="main-content"><div class="container-fluid py-3"><?php $moduleHeaderTitle='Client Baseline';$moduleHeaderSubtitle='Host-Identität und lokaler Monit-Zugang. Software-Rollout erfolgt ausschliesslich über Deploy-Profile / Git Deploy.';$moduleHeaderIcon='bi bi-layers';require __DIR__.'/../standalone/layout/module_header.php';?>
<?php require __DIR__.'/../standalone/layout/managed_hosts_tabs.php'; ?>
<div id="msg"></div>
<div class="card mb-3"><div class="card-body d-flex flex-wrap gap-2 align-items-end"><div><label class="form-label small fw-semibold">Zielserver</label><select id="server" class="form-select" style="min-width:260px"></select></div><button id="reload" class="btn btn-outline-secondary"><i class="bi bi-arrow-clockwise me-1"></i>Status laden</button><div class="ms-auto small text-body-secondary">Baseline: Config Agent + Monit-Zugang. Softwarepakete, Alloy und Exporter werden über Git Deploy verteilt.</div></div></div>
<div class="bl-grid mb-3">
 <div class="bl-card"><div class="d-flex justify-content-between"><h5>Config Agent</h5><span id="agentState"></span></div><div class="bl-kv"><span>Version</span><strong id="agentVersion">—</strong><span>Dienst</span><strong id="agentService">—</strong><span>Host-ID</span><strong id="hostId">—</strong><span>Labels</span><strong id="hostLabels">—</strong></div><div class="form-text mt-3">Steuerkanal des Config Managers. Auf registrierten Hosts bereits vorhanden.</div></div>
 <div class="bl-card"><div class="d-flex justify-content-between"><h5>Monit</h5><span class="badge text-bg-secondary">RPM verwaltet</span></div><div class="bl-kv"><span>Paket</span><strong id="monitPkg">—</strong><span>Dienst</span><strong id="monitService">—</strong><span>Zugang</span><strong id="monitCred">—</strong><span>Status-Zugriff</span><strong id="monitProbe">nicht geprüft</strong><span>Exporter-Paket</span><strong id="monitExporter">—</strong></div><ul class="bl-install-list"><li>lokaler HTTP/XML-Zugang <code>127.0.0.1:2812</code></li><li>Secret <code>/var/lib/service/config-agent/secrets/monit-status.env</code></li><li>Benutzer/Passwort setzen oder rotieren</li><li>Verbindung für Server Health testen</li><li>Monit-Paket, Exporter und Alloy werden hier <strong>nicht</strong> installiert</li></ul><div class="bl-sep"></div><div class="alert alert-secondary py-2 small mb-2"><strong>Prinzip:</strong> Monit bleibt lokal auf <code>127.0.0.1</code>. Das Passwort wird auf dem Zielserver als geschütztes Secret gespeichert. Der Config Agent verwendet diesen Zugang automatisch für Server Health.</div><div class="row g-2"><div class="col-md-5"><label class="form-label small">Bind-Adresse</label><input id="monitBind" class="form-control form-control-sm" value="127.0.0.1"></div><div class="col-md-3"><label class="form-label small">Port</label><input id="monitPort" type="number" class="form-control form-control-sm" value="2812"></div><div class="col-md-4"><label class="form-label small">Benutzer</label><input id="monitUser" class="form-control form-control-sm" value="monitadmin"></div><div class="col-12"><label class="form-label small">Passwort setzen / rotieren</label><input id="monitPass" type="password" class="form-control form-control-sm" autocomplete="new-password" placeholder="leer lassen = vorhandenes Passwort beibehalten"><div class="form-text">Neues Passwort: mindestens 12 Zeichen. Wird nicht im Browser zurückgelesen.</div></div></div><div class="d-flex flex-wrap gap-2 mt-2"><button id="saveMonit" class="btn btn-sm btn-success">Speichern & aktivieren</button><button id="testMonit" class="btn btn-sm btn-outline-primary">Verbindung testen</button></div><div class="form-text mt-2">Secret: <code id="monitSecretPath">/var/lib/service/config-agent/secrets/monit-status.env</code> · erwartet: <code>0600 root:root</code>. Service-spezifische Monit-Checks bleiben Git-/Managed-Config-konfiguriert. Softwareinstallation erfolgt über das Deploy-Profil <code>observability-client</code>.</div></div>

</div>
<div class="card"><div class="card-header fw-semibold">Klare Trennung</div><div class="card-body"><div class="row"><div class="col-md-6"><h6>Client Baseline</h6><ul><li>Config Agent / Host-ID</li><li>Monit HTTP/XML-Zugang</li><li>Monit Credential</li><li>Server-Health-Verbindungstest</li></ul></div><div class="col-md-6"><h6>Deployment über Git</h6><ul><li><strong>Deploy-Profil:</strong> <code>observability-client</code></li><li>Monit-Paket</li><li>Grafana Alloy</li><li>Monit Prometheus Exporter</li><li>Alloy Basiskonfiguration</li></ul><a class="btn btn-sm btn-outline-primary" href="git_deploy.php">Git Deploy öffnen</a></div></div></div></div>
</div></main><?php require MMBB_UI.'/includes/js.php';?>
<script>
const CSRF=<?=json_encode($csrf)?>,DEFAULT_SERVER=<?=json_encode(trim((string)($_GET['server']??'')))?>,$=id=>document.getElementById(id);let DATA={};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function msg(t,type='info'){$('msg').innerHTML=`<div class="alert alert-${type} py-2">${esc(t)}</div>`}
async function api(u,o={}){const r=await fetch(u,o),j=await r.json().catch(()=>({ok:false,error:'Ungültige Antwort'}));if(!r.ok||j.ok===false)throw new Error(j.error||`HTTP ${r.status}`);return j}
async function load(){try{const j=await api('client_baseline.php?api=load&server='+encodeURIComponent($('server').value));DATA=j.info.baseline||{};const ident=j.info.identity||{};$('hostId').textContent=ident.host_id||'—';$('hostLabels').textContent=Object.entries(ident.labels||{}).map(([k,v])=>k+'='+v).join(', ')||'—';$('agentVersion').textContent=DATA.config_agent?.version||'—';$('agentService').textContent=DATA.config_agent?.service?.active?'aktiv':'inaktiv';$('agentState').innerHTML=DATA.config_agent?.service?.active?'<span class="badge text-bg-success">OK</span>':'<span class="badge text-bg-danger">Fehler</span>';const m=DATA.monit||{},mc=m.configuration||{};$('monitPkg').textContent=m.installed?`installiert ${m.version||''}`:'nicht installiert';$('monitService').textContent=m.service?.active?'aktiv':(m.installed?'inaktiv':'—');$('monitBind').value=mc.bind||'127.0.0.1';$('monitPort').value=mc.port||2812;$('monitUser').value=mc.username||'monitadmin';$('monitCred').innerHTML=mc.secret_present?'<span class="text-success">gesetzt</span>':'<span class="text-warning">nicht gesetzt</span>';$('monitSecretPath').textContent=mc.secret_file||'/var/lib/service/config-agent/secrets/monit-status.env';const me=m.exporter||{};$('monitExporter').innerHTML=me.healthy?`<span class="text-success">aktiv · ${esc(me.version||'')}</span>`:(me.installed?'<span class="text-warning">installiert / nicht bereit</span>':'<span class="text-body-secondary">nicht installiert</span>');$('monitProbe').textContent='nicht geprüft';const mon=!!m.installed;['monitBind','monitPort','monitUser','monitPass','saveMonit','testMonit'].forEach(id=>$(id).disabled=!mon);msg(mon?'Baseline-Status geladen.':'Monit ist nicht installiert. Bitte zuerst das Deploy-Profil observability-client ausrollen.',mon?'success':'warning')}catch(e){msg(e.message,'danger')}finally{window.setTimeout(()=>{if(window.mmbbBusyReset)window.mmbbBusyReset()},0)}}
async function post(action,extra={}){return api('client_baseline.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({csrf_token:CSRF,server_name:$('server').value,action,...extra})})}
async function init(){const j=await api('client_baseline.php?api=summary');$('server').innerHTML=j.servers.map(s=>`<option>${esc(s.name)}</option>`).join('');if(DEFAULT_SERVER&&j.servers.some(s=>s.name===DEFAULT_SERVER))$('server').value=DEFAULT_SERVER;if(j.servers.length)await load()}
$('reload').onclick=load;$('server').onchange=load;$('saveMonit').onclick=async()=>{try{await post('monit_config',{config:{bind:$('monitBind').value,port:Number($('monitPort').value),username:$('monitUser').value,password:$('monitPass').value}});$('monitPass').value='';msg('Monit-Zugang und Credential gespeichert.','success');await load()}catch(e){msg(e.message,'danger')}};$('testMonit').onclick=async()=>{try{$('monitProbe').innerHTML='<span class="text-body-secondary">prüfe…</span>';const r=await post('monit_test');$('monitProbe').innerHTML='<span class="text-success">OK'+(r.result?.version?' · '+esc(r.result.version):'')+'</span>';msg('Config Agent kann Monit lokal authentisiert auslesen.','success')}catch(e){$('monitProbe').innerHTML='<span class="text-danger">Fehler</span>';msg('Monit-Test fehlgeschlagen: '+e.message,'danger')}};init();
</script></body></html>
